from llama_index.core.prompts import ChatPromptTemplate, ChatMessage

few_shot_prompt = ChatPromptTemplate(message_templates=[
    ChatMessage(role="system", content="You are an intelligent assistant that helps users retrieve accurate and context-aware information from a curated knowledge base."),
    ChatMessage(role="user", content="How can I get health insurance?"),
    ChatMessage(role="assistant", content="If you're in Texas, you can visit [Healthcare.gov](http://www.healthcare.gov), a federal platform that provides health insurance options. This program is available in your state."),
    ChatMessage(role="user", content="Where can I apply for health benefits?"),
    ChatMessage(role="assistant", content="Texans can apply for coverage through [Healthcare.gov](http://www.healthcare.gov), which is supported in Texas by the U.S. Centers for Medicare & Medicaid Services."),
    ChatMessage(role="user", content="{query_str}"),
    ChatMessage(role="user", content="Where can seniors get assistance in PA?"),
    ChatMessage(role="assistant", content="You can find senior services through the [PA Senior Services Resource Guide](<link from curated dataset>).\n\nThis resource includes:\n- Meal assistance programs\n- Transportation services\n- Healthcare support for seniors\n- Housing assistance\n- Caregiver resources\n\nPennsylvania locations included:\n- Philadelphia Senior Services Office\n- Allegheny County Area Agency on Aging (Pittsburgh)\n- Erie County Senior Center\n- Lancaster Aging Services\n- Dauphin County Office of Aging (Harrisburg)"),
    ChatMessage(role="user", content="How do I find job training programs?"),
    ChatMessage(role="assistant", content="You can find job training opportunities through the [PA Career Development Network](<link from curated dataset>).\n\nThis resource offers:\n- Skills training programs\n- Apprenticeship listings\n- Resume and career counseling services\n- Job fairs and hiring events\n- Workforce reentry support\n\nPennsylvania locations available in the dataset:\n- Philadelphia CareerLink\n- Pittsburgh Job Training Center\n- Erie Workforce Development Office\n- Lancaster Career Services\n- Harrisburg CareerLink"),
    ChatMessage(role="user", content="Where do I apply for housing help?"),
    ChatMessage(role="assistant", content="Housing assistance programs can be found in the [Pennsylvania Housing Support Directory](<link from curated dataset>).\n\nThis resource provides:\n- Rental assistance applications\n- Emergency housing contacts\n- Affordable housing program listings\n- Information on eviction prevention\n- Local housing authority contacts\n\nKey Pennsylvania locations included:\n- Philadelphia Housing Authority\n- Allegheny County Housing Office (Pittsburgh)\n- Lancaster County Housing Support\n- Erie Housing Authority\n- Dauphin County Housing Services (Harrisburg)"),
    ChatMessage(role="user", content="How can I apply for healthcare benefits?"),
    ChatMessage(role="assistant", content="You can apply for healthcare benefits using the [PA Benefits Portal](<link from curated dataset>).\n\nFrom this resource, you can:\n- Apply for health coverage\n- Check eligibility for assistance programs\n- Renew existing benefits\n- Find local enrollment offices\n- Access customer support contacts\n\nLocations in Pennsylvania available in this dataset include:\n- Philadelphia Health Office\n- Pittsburgh Health Center\n- Erie Benefits Office\n- Lancaster Health Services\n- Harrisburg Enrollment Center"),
])