name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ORCANE

    permissions:
      id-token: write   # for OIDC auth
      contents: read
      
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: az acr login --name orcaneersarc

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            orcaneersarc.azurecr.io/llamaindex:${{ github.sha }}
            orcaneersarc.azurecr.io/llamaindex:latest
          cache-from: type=registry,ref=orcaneersarc.azurecr.io/llamaindex:latest
          cache-to: type=inline

      - name: Deploy to Container App
        run: |
          az containerapp update \
            --name orcaneers-app-backend \
            --resource-group orcaneeers-rg \
            --image orcaneersarc.azurecr.io/llamaindex:${{ github.sha }}
