name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: az acr login --name orcaneersArc

      - name: Build and push image
        run: |
          docker build -t orcaneersarc.azurecr.io/llamaindex:${{ github.sha }} ./backend
          docker push orcaneersarc.azurecr.io/llamaindex:${{ github.sha }}

      - name: Deploy to Container App
        run: |
          az containerapp update \
            --name orcaneers-app-backend \
            --resource-group orcaneeers-rg \
            --image orcaneersarc.azurecr.io/llamaindex:${{ github.sha }}
